### ISSUE TITLE
5W2H

### ISSUE THREAD

**Issue by victorleaoo** [UnBArqDsw2022-2/2022.2_G5#1]
Realização do artefato do 5W2H

-----------------------------------

Tarefas:

- [x]  Realizar o artefato (introdução + metodologia)
- [ ]  Revisão do artefato (correção + complemento)

-----------------------------------

Critérios de aceitação:

- [x] Introdução
- [x] Metodologia
- [x] 5W2H
- [x] Referências
- [x] Histórico de Versão

-----------------------------------

Responsáveis:
- Abraão
- Caio

**Comment by Abraao1231** [comment]
Documento já foi criado, aguardando revisão
